name: sequel-combine

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    env:
      WORKING_DIRECTORY: sequel-combine
    strategy:
      matrix:
        ruby:
          - '3.1.1'
          - '3.0.4'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        working-directory: ${{ env.WORKING_DIRECTORY }}
    - name: Run tests
      run: bundle exec rake
      working-directory: ${{ env.WORKING_DIRECTORY }}
